# Generated by Django 5.1.7 on 2025-03-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('E', 'Euro'), ('U', 'United States Dollar'), ('R', 'Russian Rub')], default='R', max_length=1),
        ),
    ]
