# Generated by Django 5.1.7 on 2025-04-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_movie_director_alter_movie_budget_alter_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='email',
            field=models.EmailField(default='bukarash@gmail.com', max_length=254),
        ),
    ]
