# Generated by Django 5.1.7 on 2025-04-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0010_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='email',
        ),
    ]
